# Generated by Django 4.2.2 on 2023-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkyurl",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="linkyurl",
            name="shortcode",
            field=models.CharField(
                blank=True, default="abc", max_length=15, unique=True
            ),
        ),
    ]
