# Generated by Django 4.2.2 on 2023-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_linkyurl_active_alter_linkyurl_shortcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkyurl",
            name="shortcode",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
