# Generated by Django 4.2.2 on 2023-06-28 16:24

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_alter_linkyurl_shortcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkyurl",
            name="url",
            field=models.CharField(
                max_length=220,
                validators=[
                    shortener.validators.validate_url,
                    shortener.validators.validate_dot_com,
                ],
            ),
        ),
    ]
